<?php

namespace AlexItDev91\LaravelTelegramBot;

use AlexItDev91\LaravelTelegramBot\DTO\Requests\TelegramBotApiRequestData;
use AlexItDev91\LaravelTelegramBot\Enums\TelegramBotApiMethod;

/**
 * Generated from docs/METHODS.md by scripts/generate-telegram-api-schema.php.
 */
final class TelegramBotApiRequestRegistry
{
    /**
     * @var array<string, class-string<TelegramBotApiRequestData>>
     */
    private const REQUESTS = [
        'addStickerToSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AddStickerToSetRequestData',
        'answerCallbackQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerCallbackQueryRequestData',
        'answerGuestQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerGuestQueryRequestData',
        'answerInlineQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerInlineQueryRequestData',
        'answerPreCheckoutQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerPreCheckoutQueryRequestData',
        'answerShippingQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerShippingQueryRequestData',
        'answerWebAppQuery' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\AnswerWebAppQueryRequestData',
        'approveChatJoinRequest' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ApproveChatJoinRequestRequestData',
        'approveSuggestedPost' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ApproveSuggestedPostRequestData',
        'banChatMember' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\BanChatMemberRequestData',
        'banChatSenderChat' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\BanChatSenderChatRequestData',
        'close' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CloseRequestData',
        'closeForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CloseForumTopicRequestData',
        'closeGeneralForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CloseGeneralForumTopicRequestData',
        'convertGiftToStars' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ConvertGiftToStarsRequestData',
        'copyMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CopyMessageRequestData',
        'copyMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CopyMessagesRequestData',
        'createChatInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CreateChatInviteLinkRequestData',
        'createChatSubscriptionInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CreateChatSubscriptionInviteLinkRequestData',
        'createForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CreateForumTopicRequestData',
        'createInvoiceLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CreateInvoiceLinkRequestData',
        'createNewStickerSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\CreateNewStickerSetRequestData',
        'declineChatJoinRequest' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeclineChatJoinRequestRequestData',
        'declineSuggestedPost' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeclineSuggestedPostRequestData',
        'deleteAllMessageReactions' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteAllMessageReactionsRequestData',
        'deleteBusinessMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteBusinessMessagesRequestData',
        'deleteChatPhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteChatPhotoRequestData',
        'deleteChatStickerSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteChatStickerSetRequestData',
        'deleteForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteForumTopicRequestData',
        'deleteMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteMessageRequestData',
        'deleteMessageReaction' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteMessageReactionRequestData',
        'deleteMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteMessagesRequestData',
        'deleteMyCommands' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteMyCommandsRequestData',
        'deleteStickerFromSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteStickerFromSetRequestData',
        'deleteStickerSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteStickerSetRequestData',
        'deleteStory' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteStoryRequestData',
        'deleteWebhook' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\DeleteWebhookRequestData',
        'editChatInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditChatInviteLinkRequestData',
        'editChatSubscriptionInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditChatSubscriptionInviteLinkRequestData',
        'editForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditForumTopicRequestData',
        'editGeneralForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditGeneralForumTopicRequestData',
        'editMessageCaption' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageCaptionRequestData',
        'editMessageChecklist' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageChecklistRequestData',
        'editMessageLiveLocation' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageLiveLocationRequestData',
        'editMessageMedia' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageMediaRequestData',
        'editMessageReplyMarkup' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageReplyMarkupRequestData',
        'editMessageText' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditMessageTextRequestData',
        'editStory' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditStoryRequestData',
        'editUserStarSubscription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\EditUserStarSubscriptionRequestData',
        'exportChatInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ExportChatInviteLinkRequestData',
        'forwardMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ForwardMessageRequestData',
        'forwardMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ForwardMessagesRequestData',
        'getAvailableGifts' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetAvailableGiftsRequestData',
        'getBusinessAccountGifts' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetBusinessAccountGiftsRequestData',
        'getBusinessAccountStarBalance' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetBusinessAccountStarBalanceRequestData',
        'getBusinessConnection' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetBusinessConnectionRequestData',
        'getChat' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatRequestData',
        'getChatAdministrators' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatAdministratorsRequestData',
        'getChatGifts' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatGiftsRequestData',
        'getChatMember' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatMemberRequestData',
        'getChatMemberCount' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatMemberCountRequestData',
        'getChatMenuButton' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetChatMenuButtonRequestData',
        'getCustomEmojiStickers' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetCustomEmojiStickersRequestData',
        'getFile' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetFileRequestData',
        'getForumTopicIconStickers' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetForumTopicIconStickersRequestData',
        'getGameHighScores' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetGameHighScoresRequestData',
        'getManagedBotAccessSettings' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetManagedBotAccessSettingsRequestData',
        'getManagedBotToken' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetManagedBotTokenRequestData',
        'getMe' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMeRequestData',
        'getMyCommands' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyCommandsRequestData',
        'getMyDefaultAdministratorRights' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyDefaultAdministratorRightsRequestData',
        'getMyDescription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyDescriptionRequestData',
        'getMyName' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyNameRequestData',
        'getMyShortDescription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyShortDescriptionRequestData',
        'getMyStarBalance' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetMyStarBalanceRequestData',
        'getStarTransactions' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetStarTransactionsRequestData',
        'getStickerSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetStickerSetRequestData',
        'getUpdates' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUpdatesRequestData',
        'getUserChatBoosts' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUserChatBoostsRequestData',
        'getUserGifts' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUserGiftsRequestData',
        'getUserPersonalChatMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUserPersonalChatMessagesRequestData',
        'getUserProfileAudios' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUserProfileAudiosRequestData',
        'getUserProfilePhotos' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetUserProfilePhotosRequestData',
        'getWebhookInfo' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GetWebhookInfoRequestData',
        'giftPremiumSubscription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\GiftPremiumSubscriptionRequestData',
        'hideGeneralForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\HideGeneralForumTopicRequestData',
        'leaveChat' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\LeaveChatRequestData',
        'logOut' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\LogOutRequestData',
        'pinChatMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\PinChatMessageRequestData',
        'postStory' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\PostStoryRequestData',
        'promoteChatMember' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\PromoteChatMemberRequestData',
        'readBusinessMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ReadBusinessMessageRequestData',
        'refundStarPayment' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RefundStarPaymentRequestData',
        'removeBusinessAccountProfilePhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RemoveBusinessAccountProfilePhotoRequestData',
        'removeChatVerification' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RemoveChatVerificationRequestData',
        'removeMyProfilePhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RemoveMyProfilePhotoRequestData',
        'removeUserVerification' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RemoveUserVerificationRequestData',
        'reopenForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ReopenForumTopicRequestData',
        'reopenGeneralForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ReopenGeneralForumTopicRequestData',
        'replaceManagedBotToken' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ReplaceManagedBotTokenRequestData',
        'replaceStickerInSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\ReplaceStickerInSetRequestData',
        'repostStory' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RepostStoryRequestData',
        'restrictChatMember' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RestrictChatMemberRequestData',
        'revokeChatInviteLink' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\RevokeChatInviteLinkRequestData',
        'savePreparedInlineMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SavePreparedInlineMessageRequestData',
        'savePreparedKeyboardButton' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SavePreparedKeyboardButtonRequestData',
        'sendAnimation' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendAnimationRequestData',
        'sendAudio' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendAudioRequestData',
        'sendChatAction' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendChatActionRequestData',
        'sendChecklist' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendChecklistRequestData',
        'sendContact' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendContactRequestData',
        'sendDice' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendDiceRequestData',
        'sendDocument' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendDocumentRequestData',
        'sendGame' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendGameRequestData',
        'sendGift' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendGiftRequestData',
        'sendInvoice' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendInvoiceRequestData',
        'sendLivePhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendLivePhotoRequestData',
        'sendLocation' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendLocationRequestData',
        'sendMediaGroup' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendMediaGroupRequestData',
        'sendMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendMessageRequestData',
        'sendMessageDraft' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendMessageDraftRequestData',
        'sendPaidMedia' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendPaidMediaRequestData',
        'sendPhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendPhotoRequestData',
        'sendPoll' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendPollRequestData',
        'sendSticker' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendStickerRequestData',
        'sendVenue' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendVenueRequestData',
        'sendVideo' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendVideoRequestData',
        'sendVideoNote' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendVideoNoteRequestData',
        'sendVoice' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SendVoiceRequestData',
        'setBusinessAccountBio' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetBusinessAccountBioRequestData',
        'setBusinessAccountGiftSettings' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetBusinessAccountGiftSettingsRequestData',
        'setBusinessAccountName' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetBusinessAccountNameRequestData',
        'setBusinessAccountProfilePhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetBusinessAccountProfilePhotoRequestData',
        'setBusinessAccountUsername' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetBusinessAccountUsernameRequestData',
        'setChatAdministratorCustomTitle' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatAdministratorCustomTitleRequestData',
        'setChatDescription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatDescriptionRequestData',
        'setChatMemberTag' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatMemberTagRequestData',
        'setChatMenuButton' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatMenuButtonRequestData',
        'setChatPermissions' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatPermissionsRequestData',
        'setChatPhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatPhotoRequestData',
        'setChatStickerSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatStickerSetRequestData',
        'setChatTitle' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetChatTitleRequestData',
        'setCustomEmojiStickerSetThumbnail' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetCustomEmojiStickerSetThumbnailRequestData',
        'setGameScore' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetGameScoreRequestData',
        'setManagedBotAccessSettings' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetManagedBotAccessSettingsRequestData',
        'setMessageReaction' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMessageReactionRequestData',
        'setMyCommands' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyCommandsRequestData',
        'setMyDefaultAdministratorRights' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyDefaultAdministratorRightsRequestData',
        'setMyDescription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyDescriptionRequestData',
        'setMyName' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyNameRequestData',
        'setMyProfilePhoto' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyProfilePhotoRequestData',
        'setMyShortDescription' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetMyShortDescriptionRequestData',
        'setPassportDataErrors' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetPassportDataErrorsRequestData',
        'setStickerEmojiList' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerEmojiListRequestData',
        'setStickerKeywords' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerKeywordsRequestData',
        'setStickerMaskPosition' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerMaskPositionRequestData',
        'setStickerPositionInSet' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerPositionInSetRequestData',
        'setStickerSetThumbnail' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerSetThumbnailRequestData',
        'setStickerSetTitle' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetStickerSetTitleRequestData',
        'setUserEmojiStatus' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetUserEmojiStatusRequestData',
        'setWebhook' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\SetWebhookRequestData',
        'stopMessageLiveLocation' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\StopMessageLiveLocationRequestData',
        'stopPoll' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\StopPollRequestData',
        'transferBusinessAccountStars' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\TransferBusinessAccountStarsRequestData',
        'transferGift' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\TransferGiftRequestData',
        'unbanChatMember' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnbanChatMemberRequestData',
        'unbanChatSenderChat' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnbanChatSenderChatRequestData',
        'unhideGeneralForumTopic' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnhideGeneralForumTopicRequestData',
        'unpinAllChatMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnpinAllChatMessagesRequestData',
        'unpinAllForumTopicMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnpinAllForumTopicMessagesRequestData',
        'unpinAllGeneralForumTopicMessages' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnpinAllGeneralForumTopicMessagesRequestData',
        'unpinChatMessage' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UnpinChatMessageRequestData',
        'upgradeGift' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UpgradeGiftRequestData',
        'uploadStickerFile' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\UploadStickerFileRequestData',
        'verifyChat' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\VerifyChatRequestData',
        'verifyUser' => 'AlexItDev91\\LaravelTelegramBot\\DTO\\Requests\\VerifyUserRequestData',
    ];

    /**
     * @return class-string<TelegramBotApiRequestData>|null
     */
    public static function requestClass(string|TelegramBotApiMethod $method): ?string
    {
        return self::REQUESTS[self::methodName($method)] ?? null;
    }

    /**
     * @return array<string, class-string<TelegramBotApiRequestData>>
     */
    public static function all(): array
    {
        return self::REQUESTS;
    }

    private static function methodName(string|TelegramBotApiMethod $method): string
    {
        return $method instanceof TelegramBotApiMethod ? $method->value : $method;
    }
}
